# Coleta e preparação de dados

In [1]:
!pip install pandas==2.0.0

Collecting pandas==2.0.0
  Downloading pandas-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas==2.0.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.0.0) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.0.0) (2024.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas==2.0.0) (1.26.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas==2.0.0) (1.16.0)
Downloading pandas-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 78.8 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.0.0 which is incompatible.
mizani 0.11.4 requires pandas>=2.1.0, but you have pandas 2.0.0 which is incompatible.
plotnine 0.13.6 requires pandas<3.0.0,>=2.1.0, but you have pandas 2.0.0 which is incompatible.
xarray 2024.9.0 requires pandas>=2.1, but you have pandas 2.0.0 which is incompatible.
Successfully installed pandas-2.0.0

In [2]:
import pandas as pd

df = pd.read_csv('/content/relatorio_vendas.csv')
df

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro
0,2018-11-09,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,encanamentos,890.66,2,142.51
1,2018-11-09,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,ferramentas,2488.60,3,746.58
2,2018-06-13,Econômica,Giovanna Lima,B2B,Rio de Janeiro,Rio de Janeiro,Sudeste,Jardinagem e paisagismo,sementes,49.71,2,23.36
3,2017-10-12,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Materiais de construção,materiais de revestimento,3255.76,5,-1302.31
4,2017-10-12,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Jardinagem e paisagismo,vasos,76.05,2,8.56
...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2018-09-30,Entrega padrão,Enrique Santos,B2C,Rio de Janeiro,Rio de Janeiro,Sudeste,Automotivo,ferramentas automotivas,123.22,1,51.75
8936,2019-11-18,Entrega padrão,Heitor Silveira,B2B,Jequié,Bahia,Nordeste,Automotivo,ferramentas automotivas,271.97,1,97.91
8937,2019-11-18,Entrega padrão,Heitor Silveira,B2B,Jequié,Bahia,Nordeste,Automotivo,pneus,700.74,5,189.20
8938,2016-01-22,Econômica,Isabel Araújo,B2C,João Pessoa,Paraíba,Nordeste,Materiais de construção,iluminação,85.84,3,13.95
8939,2019-05-05,Econômica,Esther Rodrigues,B2C,Mossoró,Rio Grande do Norte,Nordeste,Jardinagem e paisagismo,mobiliário de exterior,826.74,2,248.02

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   vendas            8940 non-null   float64
 10  quantidade        8940 non-null   int64
 11  lucro             8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.2+ KB

In [4]:
df['data_pedido'] = pd.to_datetime(df['data_pedido'])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   vendas            8940 non-null   float64
 10  quantidade        8940 non-null   int64
 11  lucro             8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.2+ KB

# Missão 1: Time de vendas

Precisamos construir uma visualização para indicar os **10 maiores clientes por total de venda**.

Com isso, a equipe de vendas pode pensar em estratégias para manter esses clientes comprando em nossa loja.

In [6]:
df_clientes_vendas = df.groupby(['nome_cliente'])['vendas'].sum().nlargest(10).copy()
df_clientes_vendas = df_clientes_vendas.reset_index()
df_clientes_vendas

            nome_cliente    vendas
0    Maria Luiza Almeida  64777.54
1        Ana Julia Pinto  51398.95
2            Ryan Farias  48178.94
3         Heitor da Mata  47610.85
4  Maria Clara Gonçalves  46946.42
5         Raquel Freitas  44826.26
6             Davi Ramos  43769.21
7            Amanda Melo  42354.27
8         Alexia Ribeiro  41238.84
9         Calebe Ribeiro  41056.70

In [7]:
df_clientes_vendas.columns = ['Clientes', 'Vendas']
df_clientes_vendas['Ranque'] = df_clientes_vendas.index + 1
df_clientes_vendas.set_index('Ranque', inplace=True)
df_clientes_vendas

                     Clientes    Vendas
Ranque
1         Maria Luiza Almeida  64777.54
2             Ana Julia Pinto  51398.95
3                 Ryan Farias  48178.94
4              Heitor da Mata  47610.85
5       Maria Clara Gonçalves  46946.42
6              Raquel Freitas  44826.26
7                  Davi Ramos  43769.21
8                 Amanda Melo  42354.27
9              Alexia Ribeiro  41238.84
10             Calebe Ribeiro  41056.70

In [8]:
s = df_clientes_vendas.style
s

In [9]:
s.format({'Vendas':'R$ {:,.2f}'})
s

In [10]:
# DataFrame com filmes bem avaliados
dados = {
    'Gênero': ['Drama', 'Comédia', 'Ação', 'Ficção Científica', 'Terror'],
    'Nota Média': [4.5, 4.3, 4.2, 4.1, 3.8],
    'Quantidade de Avaliações': [1500, 1200, 1000, 800, 600]
}

df_filmes = pd.DataFrame(dados)

# Adiciona um rank de popularidade baseado no valor das avaliações
df_filmes['Rank'] = df_filmes['Quantidade de Avaliações'].rank(method='dense', ascending=False).astype(int)

# Define a coluna 'Rank' como índice do DataFrame
df_filmes.set_index('Rank', inplace=True)
# Objeto style
s_filme = df_filmes.style

# Criar um arquivo HTML
s_filme.to_html('estilo_html.html', index = False)

# Criar um arquivo Excel
s_filme.to_excel('estilo_xlsx.xlsx', engine='openpyxl')

# Criar um arquivo LaTeX
with open('estilo_latex.tex', 'w') as f:
  f.write(s_filme.to_latex())

Desafio Aula 01 - O primeiro desafio é construir uma visualização que permita identificar quais países mais solicitaram produtos por pedidos para que assim possa ser feito um estudo quanto a distribuição e logística de produtos.

In [11]:
df_desafio = pd.read_csv('/content/loja_livro_filmes.csv')
df_desafio

,pais,id_cliente,data_pedido,data_chegada,tipo_compra,numero_pedido,tamanho_pacote,unidades,custo_empacotamento,custo_envio,tipo_desconto,categoria,tipo_consumo,tipo_cliente,custo_produto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Pacote pequeno,1,3.0,5.99,Sem desconto,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Pacote pequeno,3,1.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Pacote pequeno,1,3.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolução,98077986,Pacote pequeno,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Pacote pequeno,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24885,Venezuela,890670789,2006-05-05,2006-05-18,Devolução,98085835,Pacote pequeno,2,1.0,6.99,Sem desconto,Livro,Alto Consumo,B2C,7.99
24886,Venezuela,892274535,2002-02-20,2002-03-08,Normal,98091414,Pacote pequeno,1,2.0,6.25,Cyber Monday,Livro,Alto Consumo,B2B,8.25
24887,Venezuela,892274535,2015-01-26,2015-02-17,Normal,98071516,Pacote pequeno,3,3.0,4.65,Sem desconto,Livro,Alto Consumo,B2B,7.65
24888,Venezuela,898039697,2002-08-22,2002-09-06,Normal,98090720,Pacote pequeno,2,2.0,4.58,Sem desconto,Livro,Alto Consumo,B2B,6.58
24889,Venezuela,898039697,2009-05-27,2009-06-17,Normal,98081676,Pacote pequeno,1,1.0,6.65,Sem desconto,Livro,Alto Consumo,B2B,7.65

In [12]:
df_desafio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24890 entries, 0 to 24889
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pais                 24890 non-null  object
 1   id_cliente           24890 non-null  int64
 2   data_pedido          24890 non-null  object
 3   data_chegada         24890 non-null  object
 4   tipo_compra          24890 non-null  object
 5   numero_pedido        24890 non-null  int64
 6   tamanho_pacote       24890 non-null  object
 7   unidades             24890 non-null  int64
 8   custo_empacotamento  24890 non-null  float64
 9   custo_envio          24890 non-null  float64
 10  tipo_desconto        24890 non-null  object
 11  categoria            24890 non-null  object
 12  tipo_consumo         24890 non-null  object
 13  tipo_cliente         24890 non-null  object
 14  custo_produto        24890 non-null  float64
dtypes: float64(3), int64(3), object(9)
memory usage: 2.8+ MB

In [13]:
df_desafio['data_pedido'] = pd.to_datetime(df_desafio['data_pedido'])
df_desafio['data_chegada'] = pd.to_datetime(df_desafio['data_chegada'])
df_desafio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24890 entries, 0 to 24889
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pais                 24890 non-null  object
 1   id_cliente           24890 non-null  int64
 2   data_pedido          24890 non-null  datetime64[ns]
 3   data_chegada         24890 non-null  datetime64[ns]
 4   tipo_compra          24890 non-null  object
 5   numero_pedido        24890 non-null  int64
 6   tamanho_pacote       24890 non-null  object
 7   unidades             24890 non-null  int64
 8   custo_empacotamento  24890 non-null  float64
 9   custo_envio          24890 non-null  float64
 10  tipo_desconto        24890 non-null  object
 11  categoria            24890 non-null  object
 12  tipo_consumo         24890 non-null  object
 13  tipo_cliente         24890 non-null  object
 14  custo_produto        24890 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(7)
memory usage: 2.8+ MB

In [14]:
df_paises = df_desafio.groupby(['pais'])['unidades'].sum().nlargest(10).copy()
df_paises = df_paises.reset_index()
df_paises

        pais  unidades
0  Argentina      5591
1    Equador      5566
2   Paraguai      5564
3       Peru      5550
4  Venezuela      5529
5   Colômbia      5504
6     Brasil      5473
7    Uruguai      5377
8      Chile      5304

In [15]:
df_paises.columns = ['País', 'Unidades de Pedidos']
df_paises['Ranque'] = df_paises.index + 1
df_paises.set_index('Ranque', inplace=True)
df_paises

             País  Unidades de Pedidos
Ranque
1       Argentina                 5591
2         Equador                 5566
3        Paraguai                 5564
4            Peru                 5550
5       Venezuela                 5529
6        Colômbia                 5504
7          Brasil                 5473
8         Uruguai                 5377
9           Chile                 5304

In [16]:
s_paises = df_paises.style
s_paises

In [17]:
s_paises.format({'Unidades de Pedidos':'{:,.0f} produtos'})
s_paises

# Missão 2: Time comercial

Precisamos construir uma visualização que permita associar o **total ganho em vendas e o total lucrado por tipo de produto**.

Isso vai permitir que o time comercial possa focar em estratégias para alavancar as rendas que ganham com cada tipo de produto vendido na loja.

In [18]:
df_venda_lucro = df.groupby(['tipo_produto'])[['vendas', 'lucro']].sum()
df_venda_lucro.index.name = 'tipo produto'
df_venda_lucro

                               vendas      lucro
tipo produto
decoração de jardim          82680.87   19880.86
encanamentos                373224.39  -11243.39
equipamentos de limpeza     542304.55   17448.30
ferramentas                 995159.43   82042.91
ferramentas automotivas     502109.33  126660.54
ferramentas de jardinagem   648880.47  106408.80
fertilizantes                53144.55   22509.86
iluminação                  275229.82   40531.09
materiais de paisagismo     150552.80   -3823.67
materiais de revestimento   629656.41  -57737.23
mobiliário de exterior      328932.37   53569.57
mudas                         8811.69    2762.88
pesticidas                  244958.41  106688.03
peças de reposição          486907.88  182297.32
pneus                      1022430.50  134923.09
sementes                     39980.49   17730.06
vasos                       696045.39   67887.28

In [19]:
estilo_produto = df_venda_lucro.style
estilo_produto

In [20]:
estilo_produto.format('R$ {:,.2f}')\
              .highlight_max(color='lightgreen')\
              .highlight_min(color='#F16165')
estilo_produto

In [21]:
estilo_produto.format('R${:,.2f}').background_gradient(cmap='Greens')
estilo_produto

In [22]:
cabecalho = {
    'selector':'th',
    'props':'font-weight: bold; font-family: Arial; text-align: center; text-transform: capitalize;'
}
estilo_produto.set_table_styles([cabecalho], overwrite= False)

Desafio - O objetivo desse desafio é construir uma visualização que permita identificar quais categorias de produto geraram mais e menos custos para a loja.

In [23]:
df_categoria_custo = df_desafio.groupby(['categoria'])[['custo_produto']].sum()
df_categoria_custo

           custo_produto
categoria
BlueRay         14191.36
CD              10514.28
Coleção         73128.59
Livro           78213.80

In [24]:
df_categoria_custo.index.name = 'Categoria do Produto'
df_categoria_custo.columns = ['Custo do Produto']
df_categoria_custo

                      Custo do Produto
Categoria do Produto
BlueRay                       14191.36
CD                            10514.28
Coleção                       73128.59
Livro                         78213.80

In [25]:
estilo_categoria = df_categoria_custo.style
estilo_categoria

In [26]:
estilo_categoria.format('R$ {:,.2f}').background_gradient(cmap='Oranges')
estilo_categoria

# Missão 3: Time de logística

Precisamos construir uma visualização que permita entender a **distribuição de pedidos por região do Brasil**.

Isso vai permitir que o time logística entenda onde é mais interessante focar material e pessoas.

In [27]:
df_regiao = pd.DataFrame(df['regiao'].value_counts())
df_regiao.columns = ['N° pedidos']
df_regiao

              N° pedidos
regiao
Sudeste             4470
Nordeste            2075
Centro-Oeste         983
Norte                779
Sul                  633

In [28]:
df_regiao.index.name = 'Regiao'

In [29]:
import numpy as np

In [30]:
porcentagem = df_regiao['N° pedidos'].to_numpy()
porcentagem = 100*porcentagem/porcentagem.sum()
porcentagem

array([50.        , 23.21029083, 10.99552573,  8.71364653,  7.08053691])

In [31]:
df_regiao['Porcentagem regiao'] = porcentagem
df_regiao

              N° pedidos  Porcentagem regiao
Regiao
Sudeste             4470           50.000000
Nordeste            2075           23.210291
Centro-Oeste         983           10.995526
Norte                779            8.713647
Sul                  633            7.080537

In [32]:
estilo_regiao = df_regiao.style
estilo_regiao

In [33]:
cabecalho = {
    'selector':'th',
    'props':'font-weight: bold; font-family: Arial; text-align: right; background-color: white;'
}
celulas = {
    'selector':'td',
    'props':'background-color: white;'
}
estilo_regiao.set_table_styles([cabecalho, celulas])

In [34]:
estilo_regiao.format({'Porcentagem regiao':'{:.2f}%'})\
            .bar(subset='Porcentagem regiao', vmin=0, vmax=100.0, color='#9CD33B')

Desafio - O desafio é construir uma visualização que permita informar a quantidade e distribuição de pedidos por tipo de desconto. Isso irá permitir que os setores da empresa entendam a demanda de produtos em cada ação promocional.

In [35]:
df_desafio.head()

,pais,id_cliente,data_pedido,data_chegada,tipo_compra,numero_pedido,tamanho_pacote,unidades,custo_empacotamento,custo_envio,tipo_desconto,categoria,tipo_consumo,tipo_cliente,custo_produto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Pacote pequeno,1,3.0,5.99,Sem desconto,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Pacote pequeno,3,1.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Pacote pequeno,1,3.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolução,98077986,Pacote pequeno,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Pacote pequeno,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88

In [36]:
df_desconto = pd.DataFrame(df_desafio['tipo_desconto'].value_counts())
df_desconto.columns = ['N° Pedidos']
df_desconto.index.name = 'Tipo de Desconto'
df_desconto

                  N° Pedidos
Tipo de Desconto
Sem desconto           13347
Cyber Monday            6922
Black Friday            1986
Liquidação              1487
Data especial           1148

In [37]:
porc = df_desconto['N° Pedidos'].to_numpy()
porc = 100*porc/porc.sum()
df_desconto['Porcentagem de Desconto'] = porc
df_desconto

                  N° Pedidos  Porcentagem de Desconto
Tipo de Desconto
Sem desconto           13347                53.623945
Cyber Monday            6922                27.810366
Black Friday            1986                 7.979108
Liquidação              1487                 5.974287
Data especial           1148                 4.612294

In [38]:
estilo_desconto = df_desconto.style
cabecalho = {
    'selector':'th',
    'props':'font-weight: bold; font-family: Calibri; text-align: center; background-color: yellow; color: blue;'
}
celulas = {
    'selector':'td',
    'props':'background-color: white; color: green;'
}
estilo_desconto.set_table_styles([cabecalho, celulas])
estilo_desconto.format({'Porcentagem de Desconto':'{:.2f}%'})\
                .bar(subset='Porcentagem de Desconto', vmin=0, vmax=100.0, color='#9CD33B')

# Missão 4: Time de logística

Novamente o time de logística deseja repensar sua estrutura e organização de fornecimento de produtos e para isso, foi pensada em uma visualização que permita identificar padrão de **quantidade de produtos solicitados por mês por departamento**.

In [39]:
df_meses = df.copy()
df_meses = df_meses.sort_values('data_pedido')
df_meses

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro
7171,2016-01-04,Entrega padrão,Ana Júlia Monteiro,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,pesticidas,55.92,2,18.87
651,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,12.04,2,-18.66
650,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,vasos,927.30,3,-220.23
649,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,sementes,40.07,3,14.52
1576,2016-01-06,Entrega padrão,Marcelo Rezende,B2C,Brasília,Distrito Federal,Centro-Oeste,Jardinagem e paisagismo,decoração de jardim,66.42,3,16.61
...,...,...,...,...,...,...,...,...,...,...,...,...
796,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,179.44,3,67.29
795,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Automotivo,pneus,309.16,7,9.27
794,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Materiais de construção,encanamentos,1098.66,4,41.20
1151,2019-12-31,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,47.27,2,15.36
1152,2019-12-31,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,70.45,2,22.01

In [40]:
df_meses['meses'] = df_meses['data_pedido'].dt.strftime('%Y - %b')
df_meses = df_meses.reset_index(drop=True)
df_meses

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro,meses
0,2016-01-04,Entrega padrão,Ana Júlia Monteiro,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,pesticidas,55.92,2,18.87,2016 - Jan
1,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,12.04,2,-18.66,2016 - Jan
2,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,vasos,927.30,3,-220.23,2016 - Jan
3,2016-01-05,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,sementes,40.07,3,14.52,2016 - Jan
4,2016-01-06,Entrega padrão,Marcelo Rezende,B2C,Brasília,Distrito Federal,Centro-Oeste,Jardinagem e paisagismo,decoração de jardim,66.42,3,16.61,2016 - Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,179.44,3,67.29,2019 - Dec
8936,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Automotivo,pneus,309.16,7,9.27,2019 - Dec
8937,2019-12-31,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Materiais de construção,encanamentos,1098.66,4,41.20,2019 - Dec
8938,2019-12-31,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,47.27,2,15.36,2019 - Dec
8939,2019-12-31,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,70.45,2,22.01,2019 - Dec

In [41]:
vendas_mensais = df_meses.pivot_table(index= 'departamento', columns= 'meses', values= 'quantidade',
                                      aggfunc= 'sum', sort= False)
vendas_mensais

meses,2016 - Jan,2016 - Feb,2016 - Mar,2016 - Apr,2016 - May,2016 - Jun,2016 - Jul,2016 - Aug,2016 - Sep,2016 - Oct,...,2019 - Mar,2019 - Apr,2019 - May,2019 - Jun,2019 - Jul,2019 - Aug,2019 - Sep,2019 - Oct,2019 - Nov,2019 - Dec
departamento,,,,,,,,,,,,,,,,,,,,,
Jardinagem e paisagismo,161,87,277,323,270,273,348,339,549,276,...,458,415,542,490,423,561,929,617,946,989
Automotivo,45,20,46,107,81,83,91,95,154,85,...,167,87,150,170,168,136,280,205,331,252
Materiais de construção,60,23,102,69,91,114,104,101,182,94,...,107,131,172,151,162,132,282,213,312,395

In [42]:
estilo_mensal = vendas_mensais.style
estilo_mensal

In [48]:
estilo_mensal.set_sticky(axis= 'index')

In [50]:
colunas = {
    'selector': '.col_heading',
    'props': 'font-weight: normal; font-family: Arial'
}
tabelas = {
    'selector': 'td,th',
    'props': 'text-align: left;'
}
index = {
    'selector': '.index_name',
    'props': 'font-weight: bold; font-family: Arial; text-align: right;'
}
estilo_mensal.set_table_styles([colunas,tabelas,index],overwrite=False)

Desafio: Nosso desafio agora é fornecer uma visualização que permita mostrar o tempo médio de entrega de pedidos durante os meses dos anos de 2013 a 2015 por cada país. Isso vai permitir analisar o desempenho da parte de transportes da empresa durante os anos e traçar um planejamento de melhorias.

In [51]:
df_desafio.head()

,pais,id_cliente,data_pedido,data_chegada,tipo_compra,numero_pedido,tamanho_pacote,unidades,custo_empacotamento,custo_envio,tipo_desconto,categoria,tipo_consumo,tipo_cliente,custo_produto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Pacote pequeno,1,3.0,5.99,Sem desconto,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Pacote pequeno,3,1.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Pacote pequeno,1,3.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolução,98077986,Pacote pequeno,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Pacote pequeno,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88

In [52]:
df_tempo_entrega = df_desafio.copy()
df_tempo_entrega = df_tempo_entrega.sort_values('data_pedido')
df_tempo_entrega = df_tempo_entrega.reset_index(drop=True)
df_tempo_entrega

,pais,id_cliente,data_pedido,data_chegada,tipo_compra,numero_pedido,tamanho_pacote,unidades,custo_empacotamento,custo_envio,tipo_desconto,categoria,tipo_consumo,tipo_cliente,custo_produto
0,Paraguai,733376144,1999-12-12,2000-01-04,Normal,98094261,Pacote grande,2,2.0,4.55,Sem desconto,Coleção,Baixo Consumo,B2B,6.55
1,Uruguai,131591686,1999-12-15,2000-01-03,Normal,98094257,Pacote grande,3,3.0,3.99,Sem desconto,Coleção,Alto Consumo,B2C,6.99
2,Uruguai,476846252,1999-12-15,2000-01-03,Normal,98094256,Pacote pequeno,1,3.0,6.14,Sem desconto,Livro,Baixo Consumo,B2C,9.14
3,Peru,561944200,1999-12-15,2000-01-04,Normal,98094260,Pacote pequeno,2,2.0,3.25,Sem desconto,Livro,Baixo Consumo,B2C,5.25
4,Paraguai,783214027,1999-12-16,2000-01-04,Devolução,98094259,Pacote grande,3,2.0,5.61,Sem desconto,Coleção,Alto Consumo,B2B,7.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24885,Uruguai,605633342,2015-12-14,2015-12-28,Normal,98069382,Pacote grande,3,1.0,5.33,Sem desconto,Coleção,Alto Consumo,B2B,6.33
24886,Peru,111962928,2015-12-15,2016-01-03,Normal,98069376,Pacote grande,1,1.0,5.99,Sem desconto,CD,Baixo Consumo,B2C,6.99
24887,Equador,758679810,2015-12-15,2016-01-04,Normal,98069373,Pacote pequeno,3,1.0,3.55,Cyber Monday,Livro,Baixo Consumo,B2C,4.55
24888,Brasil,436608095,2015-12-15,2015-12-26,Devolução,98069377,Pacote pequeno,1,3.0,3.20,Sem desconto,Livro,Alto Consumo,B2B,6.20
24889,Colômbia,667298873,2015-12-15,2016-01-02,Normal,98069374,Pacote grande,2,1.0,3.20,Sem desconto,Coleção,Alto Consumo,B2C,4.20

In [62]:
df_tempo_entrega = df_tempo_entrega[df_tempo_entrega['data_pedido'] >= '2013-01-01']
df_tempo_entrega['meses'] = df_tempo_entrega['data_pedido'].dt.strftime('%Y - %b')
tempo_entrega = (df_tempo_entrega['data_chegada'] - df_tempo_entrega['data_pedido']).dt.days
df_tempo_entrega['Tempo de Entrega'] = tempo_entrega
tempo = df_tempo_entrega.pivot_table(index= 'pais', columns= 'meses', values= 'Tempo de Entrega',
                                     aggfunc='mean', sort=False)
tempo

meses,2013 - Jan,2013 - Feb,2013 - Mar,2013 - Apr,2013 - May,2013 - Jun,2013 - Jul,2013 - Aug,2013 - Sep,2013 - Oct,...,2015 - Mar,2015 - Apr,2015 - May,2015 - Jun,2015 - Jul,2015 - Aug,2015 - Sep,2015 - Oct,2015 - Nov,2015 - Dec
pais,,,,,,,,,,,,,,,,,,,,,
Chile,90.210526,341.235294,470.111111,351.700000,195.545455,99.733333,307.230769,207.923077,321.062500,137.700000,...,606.280000,424.064516,423.428571,353.826087,432.642857,447.473684,314.111111,502.290323,406.920000,254.909091
Uruguai,180.882353,201.266667,146.523810,251.058824,12.500000,555.250000,217.789474,161.823529,117.333333,90.000000,...,231.840000,395.695652,502.352941,360.043478,349.481481,280.590909,346.000000,453.333333,434.125000,184.416667
Venezuela,216.047619,267.500000,219.400000,221.538462,180.875000,315.769231,282.416667,393.400000,405.157895,187.142857,...,307.562500,619.318182,413.482759,442.909091,443.086957,236.684211,258.384615,327.423077,271.105263,187.750000
Argentina,321.913043,314.214286,356.000000,481.173913,346.416667,309.318182,351.894737,171.750000,342.200000,149.388889,...,324.666667,467.695652,264.590909,529.888889,374.680000,506.900000,437.333333,299.178571,317.960000,293.125000
Equador,718.812500,16.928571,80.666667,206.214286,178.375000,233.000000,317.882353,252.238095,205.384615,479.153846,...,338.862069,277.608696,440.347826,566.526316,279.642857,425.280000,337.296296,238.416667,335.052632,151.000000
Colômbia,339.461538,293.066667,328.846154,136.727273,580.142857,211.050000,377.928571,643.800000,139.300000,570.000000,...,452.520000,328.941176,433.173913,438.862069,399.000000,433.913043,435.480000,462.631579,149.952381,393.777778
Brasil,238.736842,520.545455,406.642857,382.636364,454.866667,232.250000,181.217391,266.133333,272.458333,213.666667,...,431.157895,432.068966,375.541667,222.555556,310.941176,455.692308,392.791667,394.181818,391.483871,241.500000
Paraguai,216.857143,384.733333,495.882353,272.285714,345.208333,263.571429,120.416667,285.285714,506.466667,351.666667,...,510.650000,372.718750,463.722222,354.541667,607.217391,405.354839,261.521739,354.650000,203.300000,107.250000
Peru,283.476190,379.052632,436.153846,193.466667,167.529412,216.076923,333.333333,371.071429,280.928571,319.375000,...,470.481481,393.833333,499.640000,332.812500,330.580645,556.277778,471.400000,204.705882,325.764706,323.090909

In [60]:
estilo_tempo = tempo.style
estilo_tempo = estilo_tempo.format('{:.2f} dias')
estilo_tempo.set_sticky(axis='index')

In [61]:
colunas = {
    'selector': '.col_heading',
    'props': 'font-weight: normal; font-family: Calibri'
}
tabelas = {
    'selector': 'td,th',
    'props': 'text-align: center;'
}
index = {
    'selector': '.index_name',
    'props': 'font-weight: bold; font-family: Arial; text-align: right;'
}
estilo_tempo.set_table_styles([colunas,tabelas,index],overwrite=False)

# Missão 5: Relatório de performance

O relatório de performance é um documento muito importante para a empresa. Nele, todos que trabalham na loja podem entender como anda a empresa. Por conta disso, tabelas bem construídas são essenciais para mostrar os dados da melhor forma.

Portanto, precisamos construir uma visualização que permita entender a **relação entre tipos de clientes e modo de envio de produtos de acordo com as vendas**. Com isso, será possível destacar no relatório qual o modo de envio e quais tipos de modo de envio mais geraram ganho em vendas.

In [63]:
df_cliente = df.pivot_table(index= 'segmento_cliente', columns= 'modo_envio', values= 'vendas',
                            aggfunc= 'sum')
df_cliente

modo_envio         24 horas  Econômica  Entrega padrão  Envio rápido
segmento_cliente
B2B               217466.05  718462.52      1884740.78     602049.56
B2C               182531.80  729176.13      2248286.96     498295.55

In [64]:
df_cliente['Total'] = df_cliente.sum(axis=1)
df_cliente.loc['Total']= df_cliente.sum()
df_cliente

modo_envio,24 horas,Econômica,Entrega padrão,Envio rápido,Total
segmento_cliente,,,,,
B2B,217466.05,718462.52,1884740.78,602049.56,3422718.91
B2C,182531.80,729176.13,2248286.96,498295.55,3658290.44
Total,399997.85,1447638.65,4133027.74,1100345.11,7081009.35

In [65]:
compra_cliente = df_cliente.style.format('{:,.2f}')
compra_cliente

In [66]:
tabela = {
    'selector': 'td, th:not(.index_name)',
    'props': 'font-weight: normal; font-family: Arial; text-align: center; background-color: white;'
}
index = {
    'selector': '.index_name',
    'props': 'font-weight: normal; text-align: right; font-style: italic; color: #696969;'
}
compra_cliente.set_table_styles([tabela, index])

In [67]:
compra_cliente.set_table_styles({
    'Total': [{
        'selector':'th',
        'props': 'border-top: 1px solid #181818'
    },
    {
        'selector':'td',
        'props': 'border-top: 1px solid #181818'
    }],
    'B2B': [{
        'selector':'th',
        'props': 'border-top: 1px solid #181818'
    },
    {
        'selector':'td',
        'props': 'border-top: 1px solid #181818'
    }]
}, overwrite= False, axis=1)

In [68]:
compra_cliente.set_table_styles({
    'Total': [{
        'selector': '.true',
        'props': 'background-color: #D8D8D8'
    }]
}, overwrite= False, axis=0)

cores_coluna = pd.DataFrame(['false', 'true', 'false'], index= df_cliente['Total'].index,
                            columns= ['Total'])
compra_cliente.set_td_classes(cores_coluna)

In [70]:
compra_cliente.set_table_styles({
    'Total': [{
        'selector': '.true',
        'props': 'background-color: #D8D8D8'
    }]
}, overwrite= False, axis=1)

cores_linha = pd.DataFrame([['false','false', 'true', 'false', 'false']], columns = df_cliente.columns,
                            index= ['Total'])

compra_cliente.set_td_classes(cores_linha)

Desafio: envolve uma visualização que permita separar os gastos de envio de cada produto (custo total) por tipo de cliente, de modo que seja possível entender o tipo de produto que mais gerou custos de envio em cada tipo de cliente. Além disso, é interessante também mostrar a distribuição desses custos por país enviado, permitindo entender também os gastos por país.

In [81]:
df_nome = df_desafio.rename(columns={'pais': 'Custo por País'})
df_pais_custo = df_nome.pivot_table(index=['tipo_cliente', 'categoria'], columns= 'Custo por País', values = 'custo_produto', aggfunc= 'sum')
df_pais_custo

Custo por País          Argentina   Brasil    Chile  Colômbia  Equador
tipo_cliente categoria
B2B          BlueRay       488.23   552.31   521.31    538.39   473.88  \
             CD            344.74   449.66   350.58    422.22   396.15
             Coleção      2824.31  2899.26  2939.29   2823.34  2747.09
             Livro        3150.77  2751.26  2809.13   2987.06  3229.24
B2C          BlueRay      1027.85  1007.18   992.12   1062.35  1004.99
             CD            785.63   860.71   620.83    668.12   666.49
             Coleção      5587.93  5053.64  5162.34   5253.09  5583.83
             Livro        5865.62  5957.59  5718.97   5781.46  5438.32

Custo por País          Paraguai     Peru  Uruguai  Venezuela
tipo_cliente categoria
B2B          BlueRay      596.74   727.11   580.81     476.67
             CD           341.49   388.17   495.02     415.60
             Coleção     2492.20  2912.78  2548.28    2969.67
             Livro       3161.33  3092.14  2872.69    2721.60
B2C          BlueRay     1095.01  1079.54   873.96    1092.91
             CD           867.01   788.82   795.89     857.15
             Coleção     5759.34  5159.96  4961.45    5450.79
             Livro       5543.30  5678.06  5809.63    5645.63

In [82]:
df_pais_custo.rename_axis(index={'tipo_cliente': 'Tipo de cliente', 'categoria': 'Categoria do produto'}, inplace = True)
df_pais_custo['Total'] = df_pais_custo.sum(axis=1)
df_pais_custo

Custo por País                        Argentina   Brasil    Chile  Colômbia
Tipo de cliente Categoria do produto
B2B             BlueRay                  488.23   552.31   521.31    538.39  \
                CD                       344.74   449.66   350.58    422.22
                Coleção                 2824.31  2899.26  2939.29   2823.34
                Livro                   3150.77  2751.26  2809.13   2987.06
B2C             BlueRay                 1027.85  1007.18   992.12   1062.35
                CD                       785.63   860.71   620.83    668.12
                Coleção                 5587.93  5053.64  5162.34   5253.09
                Livro                   5865.62  5957.59  5718.97   5781.46

Custo por País                        Equador  Paraguai     Peru  Uruguai
Tipo de cliente Categoria do produto
B2B             BlueRay                473.88    596.74   727.11   580.81  \
                CD                     396.15    341.49   388.17   495.02
                Coleção               2747.09   2492.20  2912.78  2548.28
                Livro                 3229.24   3161.33  3092.14  2872.69
B2C             BlueRay               1004.99   1095.01  1079.54   873.96
                CD                     666.49    867.01   788.82   795.89
                Coleção               5583.83   5759.34  5159.96  4961.45
                Livro                 5438.32   5543.30  5678.06  5809.63

Custo por País                        Venezuela     Total
Tipo de cliente Categoria do produto
B2B             BlueRay                  476.67   4955.45
                CD                       415.60   3603.63
                Coleção                 2969.67  25156.22
                Livro                   2721.60  26775.22
B2C             BlueRay                 1092.91   9235.91
                CD                       857.15   6910.65
                Coleção                 5450.79  47972.37
                Livro                   5645.63  51438.58

In [90]:
estilo_pais = df_pais_custo.style.format('${:,.2f}')
estilo_pais

In [97]:
tabela = {
    'selector': 'td, th, th:not(.index_name)',
    'props': 'font-weight: normal; font-family: Calibri; text-align: center; background-color: white;'
}
index = {
    'selector': '.index_name',
    'props': 'font-weight: bold; font-family: Calibri; text-align: right;'
}
estilo_pais.set_table_styles([tabela, index])
estilo_pais.set_table_styles({
    ('B2B', 'BlueRay'): [{'selector': 'th', 'props': 'border-top: 1px solid #181818'},
              {'selector': 'td', 'props': 'border-top: 1px solid #181818'}],
    ('B2B', 'Livro'): [{'selector': 'th', 'props': 'font-weight: bold'}],
    ('B2C', 'Livro'): [{'selector': 'th', 'props': 'font-weight: bold'}],
}, overwrite=False, axis=1)

estilo_pais.set_table_styles({
    'Total': [{
        'selector': '.true',
        'props': 'font-weight: bold; color: blue; background-color: #D8D8D8'
    }]
},overwrite=False,axis=0)

cores_coluna = pd.DataFrame(['false','false','false','true','false','false','false','true'],index= df_pais_custo['Total'].index,
                            columns = ['Total'])

estilo_pais.set_td_classes(cores_coluna)